"""empty message

Revision ID: 341489a97fe0
Revises: 08e501bf74e0
Create Date: 2025-12-10 22:33:47.276231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341489a97fe0'
down_revision = '08e501bf74e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'level', ['level_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('level_id')

    # ### end Alembic commands ###
